//go:build darwin

package fs

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// requireSandboxExec skips the enforcement proof when sandbox-exec is
// unavailable — UNLESS NOCKLOCK_SANDBOX_REQUIRE=1, under which the skip becomes
// a HARD FAILURE. The macOS CI job (macos-enforce) sets that var so a runner
// that has lost sandbox-exec can never report green by silently skipping the
// only proof of the SBPL fence's runtime enforcement. Mirrors the netns suite's
// "a skip is not a pass" discipline (strictlyRequired).
func requireSandboxExec(t *testing.T) {
	t.Helper()
	if err := EnsureSandboxExecAvailable(); err != nil {
		if os.Getenv("NOCKLOCK_SANDBOX_REQUIRE") == "1" {
			t.Fatalf("sandbox-exec unavailable: %v; NOCKLOCK_SANDBOX_REQUIRE=1 forbids skipping", err)
		}
		t.Skipf("sandbox-exec unavailable: %v", err)
	}
}

// TestSeatbeltEnforcement_RealSandboxExec is the end-to-end proof on real macOS:
// a profile generated by GenerateProfile, run via WrapArgv + sandbox-exec, must
// actually DENY reads of a fenced directory while ALLOWING reads elsewhere. This
// is what makes the fence real rather than theoretical.
func TestSeatbeltEnforcement_RealSandboxExec(t *testing.T) {
	requireSandboxExec(t)

	base := t.TempDir()
	secretDir := filepath.Join(base, "secrets")
	allowedDir := filepath.Join(base, "project")
	if err := os.Mkdir(secretDir, 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(allowedDir, 0700); err != nil {
		t.Fatal(err)
	}
	secretFile := filepath.Join(secretDir, "id_rsa")
	allowedFile := filepath.Join(allowedDir, "ok.txt")
	if err := os.WriteFile(secretFile, []byte("SUPER-SECRET"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(allowedFile, []byte("fine"), 0600); err != nil {
		t.Fatal(err)
	}

	profile, err := GenerateProfile([]string{secretDir})
	if err != nil {
		t.Fatalf("GenerateProfile: %v", err)
	}
	pf, err := WriteProfile(profile)
	if err != nil {
		t.Fatalf("WriteProfile: %v", err)
	}
	defer os.Remove(pf)

	run := func(target string) (string, error) {
		argv, err := WrapArgv(pf, []string{"/bin/cat", target})
		if err != nil {
			t.Fatalf("WrapArgv: %v", err)
		}
		out, err := exec.Command(argv[0], argv[1:]...).CombinedOutput()
		return string(out), err
	}

	// Allowed path: should succeed and return content.
	if out, err := run(allowedFile); err != nil {
		t.Errorf("allowed file read failed under fence: err=%v out=%q", err, out)
	} else if got := string(out); got != "fine" {
		t.Errorf("allowed file content = %q, want %q", got, "fine")
	}

	// Fenced path: must be denied (non-nil error, secret not leaked).
	out, err := run(secretFile)
	if err == nil {
		t.Errorf("FENCE FAILED OPEN: secret read succeeded under fence: %q", out)
	}
	if strings.Contains(out, "SUPER-SECRET") {
		t.Errorf("FENCE LEAKED SECRET: output contained the secret: %q", out)
	}
}
