//go:build darwin

package fs

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// requireSandboxExec skips the enforcement proof when sandbox-exec is
// unavailable — UNLESS NOCKLOCK_SANDBOX_REQUIRE=1, under which the skip becomes
// a HARD FAILURE. The macOS CI job (macos-enforce) sets that var so a runner
// that has lost sandbox-exec can never report green by silently skipping the
// only proof of the SBPL fence's runtime enforcement. Mirrors the netns suite's
// "a skip is not a pass" discipline (strictlyRequired).
func requireSandboxExec(t *testing.T) {
	t.Helper()
	if err := EnsureSandboxExecAvailable(); err != nil {
		if os.Getenv("NOCKLOCK_SANDBOX_REQUIRE") == "1" {
			t.Fatalf("sandbox-exec unavailable: %v; NOCKLOCK_SANDBOX_REQUIRE=1 forbids skipping", err)
		}
		t.Skipf("sandbox-exec unavailable: %v", err)
	}
}

// TestSeatbeltEnforcement_RealSandboxExec is the end-to-end proof on real macOS:
// a profile generated by GenerateProfile, run via WrapArgv + sandbox-exec, must
// actually DENY reads of a fenced directory while ALLOWING reads elsewhere. This
// is what makes the fence real rather than theoretical.
func TestSeatbeltEnforcement_RealSandboxExec(t *testing.T) {
	requireSandboxExec(t)

	base := t.TempDir()
	secretDir := filepath.Join(base, "secrets")
	allowedDir := filepath.Join(base, "project")
	if err := os.Mkdir(secretDir, 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(allowedDir, 0700); err != nil {
		t.Fatal(err)
	}
	secretFile := filepath.Join(secretDir, "id_rsa")
	allowedFile := filepath.Join(allowedDir, "ok.txt")
	if err := os.WriteFile(secretFile, []byte("SUPER-SECRET"), 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(allowedFile, []byte("fine"), 0600); err != nil {
		t.Fatal(err)
	}

	profile, err := GenerateProfile([]string{secretDir})
	if err != nil {
		t.Fatalf("GenerateProfile: %v", err)
	}
	pf, err := WriteProfile(profile)
	if err != nil {
		t.Fatalf("WriteProfile: %v", err)
	}
	defer os.Remove(pf)

	run := func(target string) (string, error) {
		argv, err := WrapArgv(pf, []string{"/bin/cat", target})
		if err != nil {
			t.Fatalf("WrapArgv: %v", err)
		}
		out, err := exec.Command(argv[0], argv[1:]...).CombinedOutput()
		return string(out), err
	}

	// Allowed path: should succeed and return content.
	if out, err := run(allowedFile); err != nil {
		t.Errorf("allowed file read failed under fence: err=%v out=%q", err, out)
	} else if got := string(out); got != "fine" {
		t.Errorf("allowed file content = %q, want %q", got, "fine")
	}

	// Fenced path: must be denied (non-nil error, secret not leaked).
	out, err := run(secretFile)
	if err == nil {
		t.Errorf("FENCE FAILED OPEN: secret read succeeded under fence: %q", out)
	}
	if strings.Contains(out, "SUPER-SECRET") {
		t.Errorf("FENCE LEAKED SECRET: output contained the secret: %q", out)
	}
}

// TestSeatbeltWriteConfinement_RealSandboxExec is the negative control for
// Phase 2: a write inside filesystem.root succeeds while a sibling directory
// in the invoking user's home is denied. The test deliberately avoids t.TempDir
// for the target paths because the profile must allow the per-user temp area.
func TestSeatbeltWriteConfinement_RealSandboxExec(t *testing.T) {
	requireSandboxExec(t)

	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		t.Fatalf("UserHomeDir: %v", err)
	}
	base, err := os.MkdirTemp(home, ".nocklock-seatbelt-")
	if err != nil {
		t.Fatalf("create home test directory: %v", err)
	}
	defer os.RemoveAll(base)

	root := filepath.Join(base, "project")
	outside := filepath.Join(base, "outside")
	stateDir := filepath.Join(root, ".nock")
	for _, dir := range []string{root, outside, stateDir} {
		if err := os.MkdirAll(dir, 0700); err != nil {
			t.Fatal(err)
		}
	}
	sensitiveDir := filepath.Join(root, "sensitive")
	if err := os.Mkdir(sensitiveDir, 0700); err != nil {
		t.Fatal(err)
	}
	sensitiveFile := filepath.Join(sensitiveDir, "credential")
	if err := os.WriteFile(sensitiveFile, []byte("SUPER-SECRET"), 0600); err != nil {
		t.Fatal(err)
	}

	profile, _, err := GenerateWriteConfinementProfile(
		[]string{sensitiveDir}, root, "read-write", stateDir, false,
	)
	if err != nil {
		t.Fatalf("GenerateWriteConfinementProfile: %v", err)
	}
	pf, err := WriteProfile(profile)
	if err != nil {
		t.Fatal(err)
	}
	defer os.Remove(pf)

	write := func(target string) error {
		t.Helper()
		argv, err := WrapArgv(pf, []string{"/bin/sh", "-c", `printf fenced > "$1"`, "sh", target})
		if err != nil {
			t.Fatal(err)
		}
		return exec.Command(argv[0], argv[1:]...).Run()
	}

	insideFile := filepath.Join(root, "inside.txt")
	if err := write(insideFile); err != nil {
		t.Fatalf("write inside root failed: %v", err)
	}
	if got, err := os.ReadFile(insideFile); err != nil || string(got) != "fenced" {
		t.Fatalf("inside-root write = %q, %v; want fenced, nil", got, err)
	}

	outsideFile := filepath.Join(outside, "outside.txt")
	if err := write(outsideFile); err == nil {
		t.Fatal("FENCE FAILED OPEN: write outside filesystem.root succeeded")
	}
	if _, err := os.Stat(outsideFile); !os.IsNotExist(err) {
		t.Fatalf("outside-root target exists after denied write: %v", err)
	}

	argv, err := WrapArgv(pf, []string{"/bin/cat", sensitiveFile})
	if err != nil {
		t.Fatal(err)
	}
	out, err := exec.Command(argv[0], argv[1:]...).CombinedOutput()
	if err == nil || strings.Contains(string(out), "SUPER-SECRET") {
		t.Fatalf("sensitive path below a write-allowed root was not read-denied: err=%v out=%q", err, out)
	}
}

// TestValidateProfileRejectsMalformedProfile is the negative control for wrap's
// preflight gate: a profile that sandbox-exec rejects must be caught before an
// agent command is ever assembled or launched.
func TestValidateProfileRejectsMalformedProfile(t *testing.T) {
	requireSandboxExec(t)

	pf, err := WriteProfile("(version 1")
	if err != nil {
		t.Fatalf("WriteProfile: %v", err)
	}
	defer os.Remove(pf)

	if err := ValidateProfile(pf); err == nil {
		t.Fatal("ValidateProfile accepted malformed SBPL; wrap could falsely report ENGAGED")
	}
}
